### ISSUE TITLE
X axis zooming during acquisition 

### ISSUE THREAD

**Issue by dzid26** [klonyyy/MCUViewer#54]
This viewport range is sample based, but could be time based:
![image](https://github.com/klonyyy/STMViewer/assets/841061/6c58d36a-6529-4a90-bf61-389417656cc4)

This is time based but doesn't work
![image](https://github.com/klonyyy/STMViewer/assets/841061/162e15cf-819a-48fe-a66c-b755c53bd8e1)

It's a "nice to have".

**Comment by klonyyy** [comment]
Please explain further. I'm not sure what you mean.

**Comment by dzid26** [comment]
I am referring to viewport X axis [time] range . 
Currently it can be only globally controlled from Acquisition settings using number of samples. 

It would be more powerful if viewport time range was controllable from the plot right click menu - using time units and maybe with the mouse- during acquisition. 

- Currently, I believe, Autofit and Min / max are ignored on time axis - when acquisition is started. 
- Zooming in and out with the mouse only works during acquisition.  

In contrast, for Y axis the range can be changed during acquisition. Although, zooming with the mouse also doesn't.

**Comment by dzid26** [comment]
The perfection would be the following:
- Mouse zooming available for X and Y when stopped _and_ during acquisition. 
- Min/max possible to adjust during stop, but not forgotten during acquisition starts, - related to https://github.com/klonyyy/STMViewer/issues/52

**Comment by klonyyy** [comment]
Please reopen/react to this post if you agree this feature is needed. I'm closing for now.
