### ISSUE TITLE
Closing Acquisition Settings window - saves the changes

### ISSUE THREAD

**Issue by dzid26** [klonyyy/MCUViewer#64]
I would expect pressing X to be equivalent with Cancel and changes not to be saved.  

<img width="742" alt="image" src="https://github.com/klonyyy/STMViewer/assets/841061/d5209f68-d3ec-473a-9950-20d59585b37b">

Devel branch.

**Comment by klonyyy** [comment]
This is linked with how the values are confirmed in the text input. Some people expect it to work without pressing the enter key, some want it to be confirmed. The text input is something I want to improve (especially in other parts of the codebase), but its not  the highest priority now.
