### ISSUE TITLE
No variables found with .elf import

### ISSUE THREAD

**Issue by thencious** [klonyyy/MCUViewer#87]
### Version/Branch:

1.0.0

### Operating system:

windows 11

### Debug probe:

ST-Link V2

### Details:

No variables found with .elf import
ELF (in ZIP, elf isn't supported)
[firmware.zip](https://github.com/user-attachments/files/17177051/firmware.zip)

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/89dc69e0-2a78-4772-a5b0-3867d05f6a0d)

**Comment by r0oland** [comment]
Have you tried changing the compiler flag for debug symbols to -g1?

That solved it for me.

**Comment by thencious** [comment]
Hi, yes i did just now, it's showing a lot of variables now, although not the current sense phase currents for which I'm only seeing these 3 options. I want current.a and current.b from current_sense.getPhaseCurrents(). Any idea what i need to do to get them?
Currently I'm only using:
  // get phase currents
  PhaseCurrent_s current = current_sense.getPhaseCurrents();
  MySerial.print("A: ");
  MySerial.println(current.a);
  MySerial.print("B: ");
  MySerial.println(current.b);
![image](https://github.com/user-attachments/assets/1c1af761-f247-4a10-8727-693922951f40)

**Comment by klonyyy** [comment]
Please make sure the variable is global i.e. it persists throughout the whole lifetime of the program. Its not possible to visualize variables which are on the stack and get destroyed after the function returns.
