### ISSUE TITLE
[Feature Request] XY plot

### ISSUE THREAD

**Issue by dweggg** [klonyyy/MCUViewer#90]
### Version/Branch:

1.0.1/ main

### Operating system:

Windows 11

### Debug probe:

No debug probe

### Microcontroller:

No MCU

### Details:

**My Issue/Question:**

Hello,

I just found this project and immediately fell in love. However, I missed a feature that I think could be useful for many: XY plots. Adding this feature would allow users to easily create scatter plots, line plots, and other XY graph formats in real time, instead of manually creating them using the CSV export.

Is this something that could be considered for future implementation? I'd be happy to help or provide more input if needed.

Thanks!

**Comment by klonyyy** [comment]
We definitely need that! I'll think about the implementation and let you know if there are ways to help. Thanks!
