### ISSUE TITLE
Variables with decimal places plot display.

### ISSUE THREAD

**Issue by Femtometer** [klonyyy/MCUViewer#97]
### Version/Branch:

1.0.1

### Operating system:

Windows 10

### Debug probe:

JLink

### Microcontroller:

HT6025

### Details:

Inter variable with 4 decimal places, too big for display, Maybe better by converting it to a float, EXP: 200.xxxx.

### Screenshots/Video:

![截图_2024-11-19_10-29-14](https://github.com/user-attachments/assets/d2c084fa-d49c-43b4-9d19-bfda6e680e83)

**Comment by klonyyy** [comment]
Hello, I don't understand the first issue, could you elaborate? It's rather a very large number which obviously does not fit the plot scale, but you can use the table view to display the number, or zoom in even more. 

The second point can, for now, be resolved by streaming to a CSV file, or lowering the saple rate.

**Comment by klonyyy** [comment]
Now I understand - you mean the fixed point support. Yes, this feature is currently being developed, and will be available in the next release (probably mid December).
